version: "3.9"

services:
  
  mongodb:
    image: mongo:7
    container_name: comp3123-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: eric123
      MONGO_INITDB_DATABASE: comp3123_assignment2
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: comp3123-mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: eric123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: mongodb://admin:eric123@mongodb:27017/admin

volumes:
  mongo_data:
